name: Build and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------
      # Backend build
      # -------------------
      - name: Setup Node for backend
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd test_api
          npm install

      - name: Build backend
        run: |
          cd test_api
          npm run build

      # -------------------
      # Frontend build
      # -------------------
      - name: Setup Node for frontend
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd test_ui
          npm install

      - name: Build frontend
        run: |
          cd test_ui
          npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Backend Deploy
        run: curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}

      - name: Trigger Frontend Deploy
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}
